name: Deploy latest build

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: my-eden-life_0.2.0_aarch64.AppImage.tar.gz
        github-token: ${{ secrets.GITHUB_TOKEN }}
        repository: pomiet/my-eden-life
        
        # run-id: 123456789