name: Deploy latest build

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        repository: pomiet/my-eden-life
        # run-id: 10267606663

        