name: Deploy latest build

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: json
        github-token: ${{ secrets.UPLOAD_PAT }}
        repository: pomiet/my-eden-life
        run-id: 10273922505
  
    - uses: actions/download-artifact@v4
      with:
        name: appimage
        github-token: ${{ secrets.UPLOAD_PAT }}
        repository: pomiet/my-eden-life
        run-id: 10273922505

    - name: Prepare artifacts
      run: |
        mkdir -p ${{ github.workspace }}/latest
        cp ${{ github.workspace }}/my-eden-life*.AppImage.tar.gz ${{ github.workspace }}/latest
        jq '.platforms["linux-aarch64"].url |= sub("^(https://github.com/pomiet/my-eden-life/releases/download/[^/]+)"; "https://pomiet.github.io/my-eden-life-publish")' ${{ github.workspace }}/latest.json > ${{ github.workspace }}/latest/latest.json
        truncate -s -1 ${{ github.workspace }}/latest/latest.json


    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
          path: '${{ github.workspace }}/latest'
  
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
    
    

        