name: Deploy latest build

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: json
        github-token: ${{ secrets.UPLOAD_PAT }}
        repository: pomiet/my-eden-life
        run-id: 10273081374
  
    - name: list artifacts
      run: cat latest.json

    - uses: actions/download-artifact@v4
      with:
        name: appimage
        github-token: ${{ secrets.UPLOAD_PAT }}
        repository: pomiet/my-eden-life
        run-id: 10273081374

    - name: list artifacts
      run: ls -la
  
    
    

        